
///// VIEWER /////
export const SET_TOOL = 'SET_TOOL';
export const SET_MINIATURE_OPEN = 'SET_MINIATURE_OPEN';
export const SET_AUTO_PAN_HOVER = 'SET_AUTO_PAN_HOVER';

///// MOUSE INTERACTIONS /////
export const MOUSE_UP = 'MOUSE_UP';
export const MOUSE_DOWN = 'MOUSE_DOWN';
export const MOUSE_ENTER = 'MOUSE_ENTER';
export const MOUSE_LEAVE = 'MOUSE_LEAVE';
export const MOUSE_MOVE = 'MOUSE_MOVE';
export const MOUSE_CLICK = 'MOUSE_CLICK';
export const MOUSE_DOUBLE_CLICK = 'MOUSE_DOUBLE_CLICK';
export const MOUSE_WHEEL = 'MOUSE_WHEEL';

///// TOUCH INTERACTIONS /////
export const TOUCH_START = 'TOUCH_START';
export const TOUCH_MOVE = 'TOUCH_MOVE';
export const TOUCH_END = 'TOUCH_END';
export const TOUCH_CANCEL = 'TOUCH_CANCEL';

///// IMPERATIVE INTERACTIONS /////
export const PAN = 'PAN';
export const ZOOM = 'ZOOM';
export const FIT_SELECTION = 'FIT_SELECTION';
export const FIT_TO_VIEWER = 'FIT_TO_VIEWER';
export const ZOOM_ON_VIEW_CENTER = 'ZOOM_ON_VIEW_CENTER';
export const SET_POINT_ON_VIEW_CENTER = 'SET_POINT_ON_VIEW_CENTER';
export const RESET = 'RESET';

///// SETTINGS /////
export const SET_DETECT_AUTO_PAN = 'SET_DETECT_AUTO_PAN';
export const SET_DETECT_PINCH_GESTURE = 'SET_DETECT_PINCH_GESTURE';
export const SET_DETECT_WHEEL = 'SET_DETECT_WHEEL';
export const SET_MODIFIER_KEYS = 'SET_MODIFIER_KEYS';
export const SET_PREVENT_PAN_OUTSIDE = 'SET_PREVENT_PAN_OUTSIDE';
export const SET_PINCH_POINT_DISTANCE = 'SET_PINCH_POINT_DISTANCE';
export const SET_PRE_PINCH_MODE = 'SET_PRE_PINCH_MODE';
export const SET_SCALE_FACTOR = 'SET_SCALE_FACTOR';
export const SET_SCALE_FACTOR_MIN = 'SET_SCALE_FACTOR_MIN';
export const SET_SCALE_FACTOR_MAX = 'SET_SCALE_FACTOR_MAX';
export const SET_SCALE_FACTOR_ON_WHEEL = 'SET_SCALE_FACTOR_ON_WHEEL';

///// GEOMETRY /////
export const SET_BOUNDING_RECT = 'SET_BOUNDING_RECT';
export const SET_VIEWER_SIZE = 'SET_VIEWER_SIZE';
export const SET_SVG_GEOMETRY = 'SET_SVG_GEOMETRY';